## nocos 配置
#nacos:
#  port: 8848
#  ipAddress: 127.0.0.1
#  namespace: dev # pro
#  #  ipAddress: nacos-standalone-mysql
#  #  namespace: prod # pro
#  username: nacos
#  password: nacos
#
#spring:
#  cloud:
#    nacos:
#      discovery:
#        username: ${nacos.username}
#        password: ${nacos.password}
#        namespace: ${nacos.namespace} # 命名空间
#        server-addr: ${nacos.ipAddress}:${nacos.port} # 配置注册中心
#      config:
#        import-check:
#          enabled: false
#        username: ${nacos.username}
#        password: ${nacos.password}
#        namespace: ${nacos.namespace} # pro
#        server-addr: ${nacos.ipAddress}:${nacos.port}
#        file-extension: yml
#        refresh-enabled: true
#        # 配置公用文件（新版本使用列表格式）
#        shared-configs:
#          - data-id: cloud-config.yml
#            refresh: true
#          - data-id: sys-config-db.yml
#            refresh: true
#          - data-id: sys-config-mq.yml
#            refresh: true
#          - data-id: sys-config-redis.yml
#            refresh: true
#          # 消息通知、消息中间件
#          - data-id: sys-config-notice.yml
#            refresh: true
