server:
  port: 8080
  servlet:
    context-path: /cart

spring:
  application:
    name: learn-shop-core-cart
  config:
    import: optional:nacos:${spring.application.name}.yml

# 购物车配置
cart:
  # Redis配置
  redis:
    database: 0
    expire: 7  # 购物车数据过期天数
    prefix: "cart"  # 键前缀
  
  # 限制配置
  limit:
    maxItems: 99  # 最大商品种类数
    maxQuantity: 999  # 单个商品最大数量
    maxTotal: 999  # 购物车最大总数量
    
  # 异步任务配置
  async:
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 100
    
  # 分布式锁配置
  lock:
    timeout: 3  # 锁超时时间（秒）
    retry: 3  # 重试次数
    
  # 数据同步配置
  sync:
    interval: 300  # 同步间隔（秒）
    batchSize: 100  # 批量同步大小
    
  # 监控配置
  monitor:
    responseTime: 500  # 响应时间阈值（毫秒）
    errorRate: 0.01  # 错误率阈值
    hitRate: 0.9  # 缓存命中率阈值

# Swagger配置
swagger:
  enabled: true
  title: 购物车服务接口文档
  description: 提供购物车相关接口
  version: 1.0.0
  contact:
    name: liuyongtao
    email: xxx@xxx.com

# 日志配置
logging:
  level:
    com.billow.cart: debug
    org.springframework: warn 