# nocos 配置
nacos:
  port: 8848
  ipAddress: 127.0.0.1
  namespace: dev # pro
  #  ipAddress: nacos-standalone-mysql
  #  namespace: prod # pro
  username: nacos
  password: nacos

spring:
  config:
    import: optional:${spring.application.name}.yml
  cloud:
    nacos:
      discovery:
        username: ${nacos.username}
        password: ${nacos.password}
        namespace: ${nacos.namespace} # 命名空间
        server-addr: ${nacos.ipAddress}:${nacos.port} # 配置注册中心
      config:
        username: ${nacos.username}
        password: ${nacos.password}
        namespace: ${nacos.namespace} # pro
        server-addr: ${nacos.ipAddress}:${nacos.port}
        file-extension: yml
        refresh-enabled: true
        # 配置公用文件（新版本使用列表格式）
        shared-configs:
          - data-id: cloud-config.yml
            refresh: true
          - data-id: sys-config-db.yml
            refresh: true
          - data-id: sys-config-mq.yml
            refresh: true
          - data-id: sys-config-redis.yml
            refresh: true
          # 消息通知、消息中间件
          - data-id: sys-config-notice.yml
            refresh: true

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/learn?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
      username: root
      password: root
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.billow.*.pojo.po
  configuration:
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl